Number1 = input("Please enter the first number :")
Number2 = input("Please enter the second number :")
Number3 = input("Please enter the third number :")
Sum = float(Number1) + float(Number2) + float(Number3)
print("The sum of the three numbers =" + str(Sum))
print("The average of the three numbers =" + str(float(Sum/3.0)))